version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.4.0
    user: root
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - ./loki-data/boltdb-shipper-active:/tmp/loki/boltdb-shipper-active
      - ./loki-data/boltdb-shipper-cache:/tmp/loki/boltdb-shipper-cache
      - ./loki-data/chunks:/tmp/loki/chunks
      - ./loki-data/compactor:/tmp/loki/compactor
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml  # Đảm bảo mount file config
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage:
  loki-data:
